Cherish-Gift/back-spring

src/main/resources/banner.txt

[doc] #3 배너 추가

---

src/main/java/cherish/backend/BackendApplication.java
src/main/java/cherish/backend/board/model/Board.java
src/main/java/cherish/backend/board/model/MonthlyBoard.java
src/main/java/cherish/backend/board/model/Recommend.java
src/main/java/cherish/backend/common/config/vault/VaultProperties.java
src/main/java/cherish/backend/common/model/BaseTimeEntity.java
src/main/java/cherish/backend/item/model/Item.java
src/main/java/cherish/backend/item/model/ItemLike.java
src/main/java/cherish/backend/item/model/ItemUrl.java
src/main/java/cherish/backend/item/model/MonthlyBoardItem.java
src/main/java/cherish/backend/item/model/RecommendItem.java
src/main/java/cherish/backend/item/repository/ItemRepository.java
src/main/java/cherish/backend/member/model/Job.java
src/main/java/cherish/backend/member/model/Member.java
src/main/resources/application.yml
src/test/java/cherish/backend/item/model/ItemTest.java
src/test/resources/application.yml

Item 관련 Entity 생성 및 이미 생성된 엔티티 다른 부분 수정했습니다. 
BaseTimeEnitity 생성후 테스트까지 완료하였습니다.
추가로 메인페이지 추천을 어드민에서 넣어줘야하기에 새로운 ERD인 recommend와  recommend_item을 생성해서 RDS 에 추가해주었습니다.(확인 부탁드립니다.)

[Feature] Item Entity, Relation Item Enitity, job 생성

---

src/main/java/cherish/backend/category/model/Category.java
src/main/java/cherish/backend/category/repository/CategoryRepository.java
src/main/java/cherish/backend/common/config/EmailConfig.java
src/main/java/cherish/backend/common/model/BaseTimeEntity.java
src/main/java/cherish/backend/member/email/EmailService.java
src/test/java/cherish/backend/category/CategoryTest.java

category entity를 생성하였습니다. test를 통해 category 계층형 구조가 잘 생성됨을 확인하였습니다!

[Feature] category entity 

---

src/main/resources/logback-spring.xml

- local 프로파일에선 콘솔에 출력, loglevel=DEBUG
- dev or main profile일 경우 서버 내에 파일로 로깅. loglevel=INFO

[logging] logback config 추가

---

build.gradle
src/main/java/cherish/backend/auth/security/SecurityUser.java
src/main/java/cherish/backend/board/model/MonthlyBoard.java
src/main/java/cherish/backend/category/model/Category.java
src/main/java/cherish/backend/category/model/Mood.java
src/main/java/cherish/backend/category/model/Situation.java
src/main/java/cherish/backend/item/model/ItemCategory.java
src/main/java/cherish/backend/item/model/ItemMood.java
src/main/java/cherish/backend/item/model/ItemSituation.java
src/main/java/cherish/backend/item/model/MonthlyBoardItem.java
src/main/java/cherish/backend/item/model/enums/ItemType.java
src/main/java/cherish/backend/member/dto/MemberFormDto.java
src/main/java/cherish/backend/member/model/Member.java
src/main/java/cherish/backend/member/model/enums/Gender.java
src/main/java/cherish/backend/member/repository/MemberRepository.java
src/main/java/cherish/backend/member/service/MemberService.java
src/test/java/cherish/backend/category/model/CategoryTest.java
src/test/java/cherish/backend/item/model/ItemTest.java
src/test/java/cherish/backend/member/MemberTest.java
src/test/resources/application.yml

Member 테이블보면서 추가해야할 요소들 추가했습니다.
제가 찾은 요소 brith와 name 정도만 추가했습니다. + rds 추가
추가로 category만 진행되어있길래 연관 필드들 생성했습니다. 
일치하지 않는 네이밍도 일치시켰습니다.
@lielocks 이 넣으신 작동안되는 프록시 비교 테스트 코드(개선전 contains 테스트 코드) 삭제했습니다.
저번부터 전체적으로 Entity 필드값이 비어 있는게 많은 것 같은데 각자 한번씩 확인하는것이 좋을 것 같습니다.

issue #22 ERD 반영 화면 설계상 부족한 필드와 RDS columns 생성

---

src/main/java/cherish/backend/test/TestRestController.java
src/main/resources/application.yml

shutdown graceful option 추가 및 테스트 진행했습니다.
RestController  직접 test 해보려고 test 폴더 하나 만들었는데 추후에 삭제하겠습니다.

issue #21 shutdown graceful option + test

---

src/main/java/cherish/backend/common/dto/ErrorResponseDto.java
src/main/java/cherish/backend/common/exception/GlobalExceptionHandler.java
src/test/java/cherish/backend/common/exception/GlobalExceptionHandlerTest.java

ErrorResponse 공통 처리항목 입니다.
이후 제가 유용하게 사용했었던 자바 빈 검증 객체에 따른 메세지도 넣었습니다. 
추가로 필요한 예외처리는 해당 클래스에서 작성하면 될듯합니다.

#27-ErrorResponse & test

---

build.gradle
src/main/java/cherish/backend/common/config/redis/RedisConfig.java
src/main/java/cherish/backend/common/config/redis/RedisProperties.java
src/main/java/cherish/backend/common/service/RedisService.java
src/main/java/cherish/backend/test/TestRestController.java
src/main/resources/application.yml
src/test/java/cherish/backend/common/service/RedisServiceTest.java
src/test/resources/application.yml

local redis 에서 작동하는 코드와 테스트 코드입니다.
**@facewise 말씀해주신것 처럼 AWS ElasticCache에서 사용하려면 EC2위에서 작동해야합니다.**
yml은 default와 크게 다른점은 없지만 명시해주기 위해 작성했습니다.

 issue #28 redis connect & test

---

src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
src/main/java/cherish/backend/common/exception/ApiRequestNotValidException.java

GlobalExceptionHandler에서 익셉션을 catch한후 에러로그 출력하는 로직을 추가했습니다.

Bug/44 common exceptionhandler에 로그 추가

---

src/main/java/cherish/backend/item/repository/ItemFilterRepository.java

findItemFilterByNameAndFilterId 메소드 원복

---

src/main/java/cherish/backend/item/constant/ItemConstant.java
src/main/java/cherish/backend/item/controller/ItemLikeController.java
src/main/java/cherish/backend/item/dto/ItemLikeDto.java
src/main/java/cherish/backend/item/dto/ItemLikeRequest.java
src/main/java/cherish/backend/item/model/ItemLike.java
src/main/java/cherish/backend/item/repository/ItemLikeRepository.java
src/main/java/cherish/backend/item/repository/ItemLikeRepositoryCustom.java
src/main/java/cherish/backend/item/repository/ItemLikeRepositoryImpl.java
src/main/java/cherish/backend/item/service/ItemLikeService.java
src/test/java/cherish/backend/item/model/ItemLikeTest.java
src/test/java/cherish/backend/item/service/ItemLikeServiceTest.java
src/test/java/cherish/backend/member/MemberTest.java

#54 상품 좋아요&저장 기능 제작 하고 노션에 작성하였습니다.

feature/ItemLike 관련 기능제작

---

src/main/java/cherish/backend/member/email/service/AwsEmailService.java
src/main/java/cherish/backend/member/email/service/EmailService.java
src/main/java/cherish/backend/member/email/service/GoogleEmailService.java
src/main/java/cherish/backend/member/email/util/EmailCodeGenerator.java
src/main/java/cherish/backend/member/service/MemberService.java
src/main/resources/application.yml
src/test/java/cherish/backend/member/email/AwsEmailServiceTest.java

- profile에 google 추가시 구글 smtp 사용
- profile에 aws 추가시 aws 사용
AWS SES 프로덕션 모드가 승인되기 전까지는 당분간 구글 smtp를 사용할 예정입니다

구글 smtp 사용한 EmailService 추가

---

src/main/java/cherish/backend/member/controller/MemberController.java
src/main/java/cherish/backend/member/model/Member.java
src/main/java/cherish/backend/member/repository/MemberRepository.java
src/main/java/cherish/backend/member/service/MemberService.java

- JWT 토큰으로 인증 후 불필요한 sql 중복 제거
- /member/info API 버그 수정
- change-info API 버그 수정
- 비밀번호 변경 update sql 실행 안되던 버그 수정

Refactor/94 remove duplicate sql & fix bug

---

src/main/java/cherish/backend/item/controller/PublicItemController.java
src/main/java/cherish/backend/item/dto/ItemInfoResponseDto.java
src/main/java/cherish/backend/item/model/Item.java
src/main/java/cherish/backend/item/repository/ItemCategoryRepository.java
src/main/java/cherish/backend/item/repository/ItemFilterRepository.java
src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
src/main/java/cherish/backend/item/repository/ItemRepository.java
src/main/java/cherish/backend/item/repository/ItemRepositoryCustom.java
src/main/java/cherish/backend/item/repository/ItemRepositoryImpl.java
src/main/java/cherish/backend/item/repository/ItemUrlRepository.java
src/main/java/cherish/backend/item/service/ItemService.java
src/test/java/cherish/backend/item/service/ItemInfoServiceTest.java

+ 봉규님과 용현님 의견처럼 임시적인 데이터가 아니라 영구적으로 관리되어야 하기 때문에 redis로 관리하는건 어려울 것 같아서 views 는 db에 직접 +1 되는것으로 수정하였습니다 !
+ api 명세서에 추가해두었습니다

상품 상세정보 api

---

src/main/java/cherish/backend/auth/security/SecurityConfig.java
src/main/java/cherish/backend/common/config/cors/CorsProperties.java
src/main/resources/application.yml

postman으로 테스트해봤을때 잘 안되는것 같네요.. 
수정하고 테스트를 다시 했습니다

allowed methods 버그 수정

---

src/main/java/cherish/backend/curation/controller/PublicCurationController.java
src/main/java/cherish/backend/curation/dto/CurationRequestParam.java
src/main/java/cherish/backend/curation/dto/CurationResponseDto.java
src/main/java/cherish/backend/curation/dto/query/CurationQueryDto.java
src/main/java/cherish/backend/curation/repository/CurationRepository.java
src/main/java/cherish/backend/curation/service/CurationService.java
src/test/java/cherish/backend/curation/controller/PublicCurationControllerTest.java
src/test/java/cherish/backend/member/MemberTest.java

- querydsl로는 도저히 안되겠어서 native query를 사용했습니다..
```sql
select t.item_id, t.score
from (select total.item_id
, count(distinct case when total.job_name = '전문직' then 1 end)
+ count(distinct case when total.category_name in ('뷰티', '식품') then 1 end)
+ count(distinct case when total.filter_name = '여성' then 1 end)
+ count(distinct case when total.filter_name = '생일' then 1 end)
+ count(distinct case when total.filter_name = '지인' then 1 end)
+ count(distinct case when total.filter_name = '존경' then 1 end)
as score
from (select i.id     as item_id
, c.name   as category_name
, j.name   as job_name
, itf.name as filter_name
from item i
inner join item_category ic on i.id = ic.item_id
inner join category c on c.id = ic.category_id
inner join item_job ij on i.id = ij.item_id
inner join job j on j.id = …
```

feature: 큐레이션 컨트롤러 validation

---

src/main/java/cherish/backend/curation/dto/CurationRequestParam.java
src/main/java/cherish/backend/member/dto/MemberFormDto.java

`@NotEmpty`는 String, Map, List 등에 해당되는데 잘못 적용했던것 수정했습니다

fix: @NotEmpty 적용 버그 수정

---

src/main/java/cherish/backend/auth/jwt/JwtTokenProvider.java
src/main/java/cherish/backend/auth/jwt/config/JwtConfig.java
src/main/java/cherish/backend/auth/jwt/config/JwtProperties.java
src/main/java/cherish/backend/auth/jwt/filter/JwtAuthenticationFilter.java
src/main/java/cherish/backend/auth/jwt/filter/JwtExceptionFilter.java
src/main/java/cherish/backend/auth/jwt/util/TokenResolver.java
src/main/java/cherish/backend/auth/security/SecurityConfig.java
src/main/java/cherish/backend/common/controller/TokenRefreshController.java
src/main/java/cherish/backend/common/service/RedisService.java
src/main/java/cherish/backend/member/controller/MemberController.java
src/main/java/cherish/backend/member/controller/PublicMemberController.java

- 로그아웃 API 추가
- 레디스에 로그아웃하는 액세스토큰을 블랙리스트로 등록
- 액세스 토큰을 검증하는 validateToken() 메소드에서 레디스 블랙리스트에 등록되어 있는지 확인

로그아웃 API 추가

---

src/main/java/cherish/backend/item/controller/PublicItemController.java
src/main/java/cherish/backend/item/dto/ItemSearchResponseDto.java
src/main/java/cherish/backend/item/repository/ItemFilterRepositoryCustom.java
src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
src/main/java/cherish/backend/item/service/ItemService.java
src/test/java/cherish/backend/item/service/ItemSearchServiceTest.java

[refactor] search response에 liked 필드 추가

---

src/main/java/cherish/backend/common/aop/GlobalExceptionHandler.java
src/main/java/cherish/backend/member/email/service/AwsEmailService.java
src/main/java/cherish/backend/member/email/service/EmailService.java
src/main/java/cherish/backend/member/email/service/GoogleEmailService.java
src/main/java/cherish/backend/member/service/MemberService.java
src/test/java/cherish/backend/member/controller/MemberControllerTest.java
src/test/java/cherish/backend/member/email/AwsEmailServiceTest.java

fix: 이메일 인증코드 형식 수정

---

src/main/java/cherish/backend/item/controller/PublicRecommendItemController.java
src/main/java/cherish/backend/item/dto/RecommendItemQueryDto.java
src/main/java/cherish/backend/item/dto/RecommendItemResponseDto.java
src/main/java/cherish/backend/item/model/Item.java
src/main/java/cherish/backend/item/repository/ItemRepository.java
src/main/java/cherish/backend/item/repository/RecommendItemRepository.java
src/main/java/cherish/backend/item/service/RecommendItemService.java

[feature] main page API 

---

src/main/java/cherish/backend/item/controller/PublicItemController.java
src/main/java/cherish/backend/item/dto/ItemSearchCondition.java
src/main/java/cherish/backend/item/repository/ItemFilterRepositoryImpl.java
src/main/java/cherish/backend/item/service/ItemService.java
src/main/resources/application.yml

[fix] search filter 동일 컬럼에 대한 필터링 조건 (situationName, gender) fix

---

src/main/java/cherish/backend/auth/security/SecurityConfig.java

클라이언트에서 JWT 토큰이 없거나 잘못된 인증 정보로 접근할 경우 기본 EntryPoint인
`Http403ForbiddenEntryPoint`가 처리하여 403 에러가 났었습니다.
403은 인증은 됐지만 인가가 안된 경우의 상태 코드로 혼란이 있어서
401 에러를 내려줄수 있는 EntryPoint를 추가했습니다

add: JWT auth정보 없을 시 401상태 만들어주는 entry point 추가
